In [ ]:
import random


pres = ["Hadj ", "Ben", "Beni", "Ait ", "Nait ", "Bey", "El", ""]
posts = ["khiter", "khemis", "sma", "djema", "yema", "arab", "ammas", "mazigh", "laarab", "rani", "dirma", "khoukh", "semis", "wassil", "yazid", "mohand", "miloud", "babour", "azour", "azoug", "hella", "lamine"]
firstNames = ["Ghiles", "M'hand", "Anis", "Samy", "Rayan", "Mohamed", "Ramy", "Walid", "Yazid", "Saida", "Léna", "Samir", "Maya","Lyna","Chiraz","Malika","Aicha","Sofia","Lynda","Sabrina","Karima","Karim","Wassila"]
name =[]
f = open("drive/MyDrive/codeWeek/names.doc", "w")
i=0
for pre in pres:
  for post in posts:
    for firstName in firstNames:
      name.append(" "+pre + post + " "+firstName+"\n")
      
      i+=1


name.append("Bouzertit Malika")  
random.shuffle(name)

for index in range(i+1):
  f.writelines(name[index])
print(name)
print(i)
f.close()





In [ ]:
with open("file.txt") as f:
    lines = f.readlines()

splited =[]
sol =0 

for line in lines:
  if "bleu" in line.lower() and "chaud" in line.lower():
    splited=line.split("cm)")
    if ("boule (pointe" in splited[0].lower() and "pleine,12" in splited[0].lower()) or ("boule (pointe" in splited[1].lower() and "pleine,12" in splited[1].lower()):
      sol +=1

print(sol)




79


In [ ]:
import random
l11 = ['grand-mère maternelle', 'grand-mère paternelle', 'tante maternelle', 'tante paternelle', 'maman']
l12= ['soeur','cousine','nièce']
l13 =['fille', 'nièce' , 'petite-fille']
NF1 =['Thilelli', 'Aya','Inès','Yasmine', 'Manel','Assia','Maryam','Maya','Leticia', 'Asma', 'Lilia', 'Sérine', 'Hana' ]
NF2=['Khadidja','Fatima','Safia','Anissa','Halima','Fouzia','Aldjia','Fetouma','Yasmina','Bachira', 'Abla','Aziza','Baya', 'Drifa']
l21 = ['frère','cousin', 'neveu']
l22=['fils', 'neveu' , 'petit-fils']
l23= [ 'grand-père maternel', 'grand-père paternel', 'oncle maternel', 'oncle paternel', 'père']
NG1 =['Djafar', 'Fares','Farid', 'Hakim','Hani','Ilias','Malik','Nacim','Omar', 'Oussama', 'Ramzi','Samir','Walid','Younes']
NG2=['Fouad','Fawzi','Hocine','Karim', 'Islem','Kamel','Khaled', 'Larbi','Azzeddine','Mourad','Nourredine','Salah','Toufik']


fFamily = open("drive/MyDrive/codeWeek/family.doc", "w")
#Famille_de_Mouna = ["Boussaad est le grand-père paternel de Mouna","Mouna est la fille de Slimane","Nadia est la maman de Mouna","Karima est la grand-mère maternelle de Mouna","Mira est la tante paternelle de Mouna", "Samy est le neveu de Mouna","Mouna est la soeur de Samir ","Samir est le père de Samy","Dounia est la belle-soeur de Mouna","Rayan est le beau-frère de Mouna","Mouna est la soeur de Sofia","Dehbia est la soeur de la grand-mère paternelle de Mouna","Ourida est la grand-mère paternelle de Rocky","Hamid est le frère de Ourida","Ferroudja est la soeur de Boussaad ","Samira est la tante maternelle de Mouna","Mouloud est le mari de Mira","Sonia est la tante maternelle de Mouna","Houda est la cousine de Mouna","Mouna est la petite-fille de Moukrane","Madjid est le frère de Karima","Nadia est la fille de Moukrane","Kahina est la tante maternelle de Mouna","Lina est la cousine de Mouna","Kahina est la maman de Lina","Nour est la soeur de Houda","Fatah est le frère de Lina","Lina est la fille de Ahmed","Riad est l’oncle maternel de Mouna","Mouna est la cousine de Lydia","Nadia est la maman de Rocky","Lydia est la fille de Riad","Dounia est la soeur de Lydia","Sarah est la maman de Lydia"]
 

family = []


for i in range (random.randint(0,50)):
    family.append(random.choice(NF2) + ' est la '  + random.choice(l11)  + ' de '  + random.choice(NF1)+ "\n")
    family.append(random.choice(NF2) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF2)+ "\n")
    family.append(random.choice(NF2) + ' est la '  + random.choice(l11)  + ' de '  + random.choice(NG1)+ "\n")
    family.append(random.choice(NG2) + ' est la '  + random.choice(l23)  + ' de '  + random.choice(NF1)+ "\n")
    
    R1= random.choice(l23)
    if R1== 'oncle maternel' or R1== 'oncle paternel':
        family.append(random.choice(NG2) + ' est l\''  + R1  + ' de '  + random.choice(NG1)+ "\n")
    else: 
        family.append(random.choice(NG2) + ' est le '  + R1  + ' de '  + random.choice(NG1)+ "\n")
    family.append(random.choice(NF1) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF1)+ "\n")
    R2 = random.choice(l21)
    if R2== 'oncle maternel' or R2== 'oncle paternel':
        family.append(random.choice(NG1) + ' est l\''  + R2  + ' de '  + random.choice(NG1)+ "\n")
    else:
        family.append(random.choice(NG1) + ' est le '  + R2  + ' de '  + random.choice(NG1)+ "\n")
    R3 = random.choice(l21)
    if R3== 'oncle maternel' or R3== 'oncle paternel':
        family.append(random.choice(NG2) + ' est l\''  + R3 + ' de '  + random.choice(NG2)+ "\n")
    else:
        family.append(random.choice(NG2) + ' est le '  + R3 + ' de '  + random.choice(NG2)+ "\n")
    family.append(random.choice(NF1) + ' est la '  + random.choice(l13)  + ' de '  + random.choice(NF2)+ "\n")
    R4 = random.choice(l22) 
    if R4== 'oncle maternel' or R4== 'oncle paternel':
        family.append(random.choice(NG1) + ' est l\''  + R4 + ' de '  + random.choice(NG2)+ "\n")
    else:
        family.append(random.choice(NG1) + ' est le '  + R4 + ' de '  + random.choice(NG2)+ "\n")


for i in range (random.randint(0,10)):
    family.append(random.choice(NF2) + ' est la '  + random.choice(l11)  + ' de '  + random.choice(NF1)+ "\n")
    family.append(random.choice(NF2) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF2)+ "\n")
    
    R1= random.choice(l23)
    if R1== 'oncle maternel' or R1== 'oncle paternel':
        family.append(random.choice(NG2) + ' est l\''  + R1  + ' de '  + random.choice(NG1)+ "\n")
    else: 
        family.append(random.choice(NG2) + ' est le '  + R1  + ' de '  + random.choice(NG1)+ "\n")
    family.append(random.choice(NF1) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF1)+ "\n")
    R2 = random.choice(l21)
    if R2== 'oncle maternel' or R2== 'oncle paternel':
        family.append(random.choice(NG1) + ' est l\''  + R2  + ' de '  + random.choice(NG1)+ "\n")
    else:
        family.append(random.choice(NG1) + ' est le '  + R2  + ' de '  + random.choice(NG1)+ "\n")

for i in range (random.randint(0,5)):
    family.append(random.choice(NF2) + ' est la '  + random.choice(l11)  + ' de '  + random.choice(NF1)+ "\n")
    family.append(random.choice(NF2) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF2)+ "\n")
    
    R1= random.choice(l23)
    if R1== 'oncle maternel' or R1== 'oncle paternel':
        family.append(random.choice(NG2) + ' est l\''  + R1  + ' de '  + random.choice(NG1)+ "\n")
    else: 
        family.append(random.choice(NG2) + ' est le '  + R1  + ' de '  + random.choice(NG1)+ "\n")

family.append(random.choice(NF2) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF2)+ "\n")

for i in range (random.randint(0,20)):
    
    family.append(random.choice(NF2) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF2)+ "\n")
    R1= random.choice(l23)
    if R1== 'oncle maternel' or R1== 'oncle paternel':
        family.append(random.choice(NG2) + ' est l\''  + R1  + ' de '  + random.choice(NG1)+ "\n")
    else: 
        family.append(random.choice(NG2) + ' est le '  + R1  + ' de '  + random.choice(NG1)+ "\n")
    R4 = random.choice(l22) 
    if R4== 'oncle maternel' or R4== 'oncle paternel':
        family.append(random.choice(NG1) + ' est l\''  + R4 + ' de '  + random.choice(NG2)+ "\n")
    else:
        family.append(random.choice(NG1) + ' est le '  + R4 + ' de '  + random.choice(NG2)+ "\n") 

        
family.append(random.choice(NF2) + ' est la '  + random.choice(l11)  + ' de '  + random.choice(NF1)+ "\n")

R3 = random.choice(l21)
if R3== 'oncle maternel' or R3== 'oncle paternel':
        family.append(random.choice(NG2) + ' est l\''  + R3 + ' de '  + random.choice(NG2)+ "\n")
else:
        family.append(random.choice(NG2) + ' est le '  + R3 + ' de '  + random.choice(NG2)+ "\n")


family.append(random.choice(NF1) + ' est la '  + random.choice(l13)  + ' de '  + random.choice(NF2)+ "\n")


family.append(random.choice(NF1) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF1)+ "\n")

R2 = random.choice(l21)
if R2== 'oncle maternel' or R2== 'oncle paternel':
    family.append(random.choice(NG1) + ' est l\''  + R2  + ' de '  + random.choice(NG1)+ "\n")
else:
    family.append(random.choice(NG1) + ' est le ' + R2  + ' de ' + random.choice(NG1)+ "\n")
    


for i in range (random.randint(0,15)):
    
    family.append(random.choice(NF2) + ' est la '  + random.choice(l12)  + ' de '  + random.choice(NF2)+ "\n")
   
    R4 = random.choice(l22) 
    if R4== 'oncle maternel' or R4== 'oncle paternel':
        family.append(random.choice(NG1) + ' est l\''  + R4 + ' de '  + random.choice(NG2)+ "\n")
    else:
        family.append(random.choice(NG1) + ' est le '  + R4 + ' de '  + random.choice(NG2)+ "\n")      

R1= random.choice(l23)
if R1== 'oncle maternel' or R1== 'oncle paternel':
    family.append(random.choice(NG2) + ' est l\''  + R1  + ' de '  + random.choice(NG1)+ "\n")    
else: 
    family.append(random.choice(NG2) + ' est le '  + R1  + ' de '  + random.choice(NG1)+ "\n")
      
family.append(random.choice(NF2) + ' est la '  + random.choice(l11)  + ' de '  + random.choice(NG1) + "\n")
family.append(random.choice(NG2) + ' est le '  + random.choice(l23)  + ' de '  + random.choice(NF1) + "\n")


print(family)
print(len(family))

for index in range(len(family)):
  fFamily.writelines(family[index])

fFamily.close()


['Fetouma est la tante paternelle de Maryam\n', 'Safia est la nièce de Safia\n', 'Bachira est la maman de Omar\n', 'Karim est la père de Asma\n', "Mourad est l'oncle paternel de Ilias\n", 'Sérine est la soeur de Aya\n', 'Hani est le cousin de Farid\n', 'Larbi est le neveu de Islem\n', 'Aya est la fille de Bachira\n', 'Djafar est le neveu de Kamel\n', 'Bachira est la tante paternelle de Yasmine\n', 'Abla est la cousine de Drifa\n', 'Aziza est la grand-mère maternelle de Younes\n', 'Islem est la grand-père paternel de Lilia\n', "Khaled est l'oncle maternel de Fares\n", 'Inès est la cousine de Inès\n', 'Oussama est le frère de Djafar\n', 'Karim est le cousin de Islem\n', 'Leticia est la fille de Drifa\n', 'Fares est le fils de Mourad\n', 'Safia est la tante paternelle de Lilia\n', 'Fouzia est la soeur de Fetouma\n', 'Bachira est la maman de Samir\n', 'Salah est la père de Manel\n', 'Fawzi est le père de Younes\n', 'Inès est la soeur de Aya\n', 'Djafar est le cousin de Malik\n', 'Hocine es

In [ ]:
import random 

pres = ["Hadj ", "Ben", "Beni", "Ait ", "Nait ", "Bey", "El", ""]
posts = ["khiter", "khemis", "sma", "djema", "yema", "arab", "ammas", "mazigh", "laarab", "rani", "dirma", "khoukh", "semis", "wassil", "yazid", "mohand", "miloud", "babour", "azour", "azoug", "hella", "lamine"]
firstNames = ["Mohamed", "M'hand", "Anis", "Ghiles", "Samy", "Rayan", "Ramy", "Walid", "Yazid", "Saida", "Léna", "Samir", "Maya","Lyna","Chiraz","Malika","Aicha","Sofia","Lynda","Sabrina","Karima","Karim","Wassila"]
name =[]

i=0
for pre in pres:
  for post in posts:
    for firstName in firstNames:
      name.append(pre + post + " "+firstName)
      
      i+=1
      
random.shuffle(name)



sang = ["A", "B", "O", "AB"]
rhesus = ["+", "-"]

typeSang =[]
f = open("drive/MyDrive/codeWeek/listHotel.doc", "w")

ffaux = open("drive/MyDrive/codeWeek/listHotelFaux.doc", "w")
i=0
for typeS in sang:
  for r in rhesus:
    typeSang.append(typeS + r)
  
anniv = []

for j in range(1,32):
  for m in range(1,13):
    for y in range(1988, 2002):
      if m==2:
        if j<29:
          anniv.append(str(j)+"/"+str(m)+"/"+str(y))
      elif m%2==0:
        if j<31:
          anniv.append(str(j)+"/"+str(m)+"/"+str(y))
      else:
        anniv.append(str(j)+"/"+str(m)+"/"+str(y))

postNum = ['06','05','07']

      
hotelList=[]
i=0
for n in name:
  i+=1
  if i<3400:
    date = random.choice(anniv)
    year = date[-3] + date[-2] + date[-1]
    numTel = random.choice(postNum) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9))
    nin = str(random.randint(0,1)) + str(random.randint(0,1)) +  year + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) +  str(random.randint(0,9))
    hotelList.append(n + "  "+ date + "  " + numTel + "  " + nin + "  " + random.choice(typeSang) + "\n")



falseList = []

for false in range(1234567, 1234637):
  date = random.choice(anniv)
  year = date[-3] + date[-2] + date[-1]
  numTel = random.choice(postNum) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9))
  nin = str(random.randint(0,3)) + str(random.randint(0,1)) +  year + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) +  str(random.randint(0,9))
  falseList.append(str(false) +" "+ str(false) + "  "+ date + "  " + numTel + "  " + nin + "  " + random.choice(typeSang) + "\n") 

for j in range(i+1,3550):
  date = random.choice(anniv)
  year = date[-3] + date[-2] + date[-1]
  numTel = str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9))
  nin = str(random.randint(0,1)) + str(random.randint(0,1)) +  year + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) +  str(random.randint(0,9))
  falseList.append(name[j] + "  "+ date + "  " + numTel + "  " + nin + "  " + random.choice(typeSang) + "\n") 

fauxSang = ["A0", "C-", "5+", "RA", "B", "++"]

for j in range(3550,3700):
  date = random.choice(anniv)
  year = date[-3] + date[-2] + date[-1]
  numTel = random.choice(postNum) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9))
  nin = str(random.randint(0,1)) + str(random.randint(0,1)) + year + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) +  str(random.randint(0,9))
  falseList.append(name[j] + "  "+ date + "  " + numTel + "  " + nin + "  " + random.choice(fauxSang) + "\n") 

fauxAnniv = ["31/04/2000", "1/0/1989", "7/13/1990", "30/02/1992", "32/03/1993", "29/11/190", "8/3/2190"]

for j in range(3700,3850):
  date = random.choice(fauxAnniv)
  year = date[-3] + date[-2] + date[-1]
  numTel = random.choice(postNum) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9))
  nin = str(random.randint(0,1)) + str(random.randint(0,1)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) +  str(random.randint(0,9))
  falseList.append(name[j] + "  "+ date + "  " + numTel + "  " + nin + "  " + random.choice(typeSang) + "\n") 

for j in range(3850,4048):
  date = random.choice(anniv)
  year = date[-3] + date[-2]
  numTel = random.choice(postNum) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9))
  nin = str(random.randint(0,1)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) + str(random.randint(0,9)) +  str(random.randint(0,9))
  falseList.append(name[j] + "  "+ date + "  " + numTel + "  " + nin + "  " + random.choice(typeSang) + "\n") 


random.shuffle(hotelList)
random.shuffle(falseList)

for index in range(0, len(hotelList)):
  f.writelines(hotelList[index])

for jndex in range(0,len(falseList)):
  ffaux.writelines(falseList[jndex])



print(len(hotelList))
print(len(falseList))
f.close()
ffaux.close()

3399
568


In [ ]:
import random

Forme = ["Boule","Pyramide"]
P1 = ["lisse","Pointe"]
P2 = ["Chaude","Froide"]
P3 = ["Blanc","Bleu"]
P4 = ["Creuse","Pleine"]
P5 = ["10 cm","12 cm"]

Liste = open("drive/MyDrive/codeWeek/armes.doc", "w")
ListeArmeSans = []
ListeArmeAvec = []

for i in Forme :
    for j in P1 :
        for k in P2 :
            for e in P3 :
                for f in P4 :
                    for s in P5 :
                        ListeArmeSans.append(i+' ('+j+','+k+','+e+','+f+','+s+')')

for arme1 in ListeArmeSans: 
  for arme2 in ListeArmeSans:
    if not (arme1==arme2):
      ListeArmeAvec.append(arme1 + " " + arme2+'\n')

random.shuffle(ListeArmeAvec)

for index in range(0, len(ListeArmeAvec)):
  Liste.writelines(ListeArmeAvec[index])

print(len(ListeArmeAvec))
Liste.close()

4032


In [ ]:
import random
import numpy as np

import re
f = open("mat6060.txt", "r")

M = []
i = 0
with open("mat6060.txt") as f:
    lines = f.readlines()


for line in lines:
  word = line.split()
  N = []
  for w in word:
    if re.match("[0-9]+", w):
      N.append(int(w))
  M.append(N)


A = np.array(M)

print(np.shape(A))

f.close()

matrice = open("drive/MyDrive/codeWeek/matrice.doc", "w")

n= 60

#n = n+2
#A= np.random.randint(6, size=(n,n))


for i in range(n-1):
    for j in range(n-1) :
        if A[i][j] == 0 :
            if (A[i][j-1] in A and (A[i][j-1] == 2 or A[i][j-1] == 5)):
                A[i][j-1] = 4
            if (A[i][j+1] in A and (A[i][j+1] == 1 or A[i][j+1] == 5 )):
                A[i][j+1] = 2
            if (A[i-1][j] in A and (A[i-1][j]  == 4 or A[i-1][j]  == 5  )):
                A[i-1][j] = 3
            if (A[i+1][j] in A and (A[i+1][j] == 3 or A[i+1][j] == 5 )):
                A[i+1][j] = 4
for i in range(n-1):
    for j in range(n-1) :
        if A[i][j] == 5 :
            if A[i][j-1] in A :
                A[i][j-1] = 2
            if A[i][j+1] in A :
                A[i][j+1] = 1
            if A[i-1][j] in A :
                A[i-1][j] = 4
            if A[i+1][j] in A:
                A[i+1][j] = 3 
print(A)

for i in range(1,n-1):
    for j in range(1,n-1) :
        A1= int(A[i][j] /100)
        A2= int((A[i][j] -A1*100)/10)
        A3 = A[i][j] -(A1*100 +A2*10) 
        
        if A3 ==1 :
            if (A[i][j-1] in A and A[i][j-1]  !=0 and A[i][j-1] !=5  )  :
                B1 = int(A[i][j-1] /100)
                B2 = int((A[i][j-1] -B1*100)/10)
                B3 = A[i][j-1] -(B1*100 +B2*10)
                if (B1 == 0 and B2 == 0 and B3!= 2 ):
                    x= min ( 2 , B3)
                    if x == 2 :
                        A[i][j-1]= B3*10+2
                        
                    else :
                        A[i][j-1]= B3+2*10
                if (B1 == 0 and B2 != 0 and B2!=2 and B3 !=2):
                    x= min ( B3, B2 , 2)
                    if x ==2 :
                        A[i][j-1] = A[i][j-1]*10 + 2
                    if x ==B3 :
                        A[i][j-1] = B3+ 2*10 + B2*100
                if (B1 != 0 and B1 != 2 and B2 != 2 and B3 !=2) :
                        A[i][j-1] = 5
                              
                                
        if (A3 == 2 or A2 ==2) :
            if (A[i][j+1] in A and A[i][j+1]  !=0 and A[i][j+1] !=5  )  :
                B1 = int(A[i][j+1] /100)
                B2 = int((A[i][j+1] -B1*100)/10)
                B3 = A[i][j+1] -(B1*100 +B2*10)
                if( B1 == 0 and B2 == 0 and B3 != 1):
                    A[i][j+1]= A[i][j+1]*10+1
                           
                if (B1 == 0 and B2 != 0 and B2!=1 and B3 !=1):
                    A[i][j+1] = A[i][j+1]*10 + 1
                if (B1 != 0 and B1 != 1 and B2 != 1 and B3 !=1) :
                    A[i][j+1] = 5
                
        if (A1 ==3 or A2 ==3 or A3 ==3)  :
            if (A[i-1][j] in A and A[i-1][j]  !=0 and A[i-1][j] !=5  )  :
                B1 = int(A[i-1][j] /100)
                B2 = int((A[i-1][j] -B1*100)/10)
                B3 = A[i-1][j] -(B1*100 +B2*10)
                if (B1 == 0 and B2 == 0 and B3 != 4):
                    A[i-1][j]= B3+4*10
                            
                if (B1 == 0 and B2 != 0 and B2 !=4 and B3 !=4):
                    A[i-1][j] = A[i-1][j]+ 4*100
                            
                if (B1 != 0 and B1 != 4 and B2 != 4 and B3 !=4) :
                    A[i-1][j] = 5
        if (A1 ==4 or A2 ==4 or A3 ==4)  :
            if (A[i+1][j] in A and A[i+1][j]  !=0 and A[i+1][j] !=5  )  :
                B1 = int(A[i+1][j] /100)
                
                B2 = int((A[i+1][j] -B1*100)/10)
                B3 = A[i+1][j] -(B1*100 +B2*10)
                if (B1 == 0 and B2 == 0 and B3 != 3):
                    x= min(3 ,A[i+1][j] )
                    if x == 3 :
                        A[i+1][j]=  B3*10+3
                    else :
                        A[i+1][j]= B3+3*10
                            
                if (B1 == 0 and B2 != 0 and B2!=3 and B3 !=3):
                    x = min (3 ,B2  )
                    if x== B2 :
                        A[i+1][j]= A[i+1][j] + 3*100
                    else :
                        A[i+1][j]= B3+ B2*100 + 3*10
                   
                if (B1 != 0 and B1 != 3 and B2 != 3 and B3 !=3) :
                    A[i+1][j] = 5
                    

 
LaMatrice = A[1:-1 , 1:-1]        

#summ = 0
#for a in A:
 #  for b in a:
  #  if not (b):
   #   summ +=1

for i in range(0,np.shape(LaMatrice)[1]):
  matrice.writelines(str(LaMatrice[i]))

print(np.array(M)==A)
print(summ)
matrice.close()
            

(60, 60)
[[ 21  21  21 ...  21  21   1]
 [ 21 421   4 ...  21  21 421]
 [  4   2   5 ...   4 421 431]
 ...
 [ 32  31   4 ...   1 321 321]
 [421   2   5 ...   0   0   0]
 [321 321   3 ...  21  21   1]]
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ... False  True  True]
 ...
 [ True  True False ...  True  True  True]
 [ True False  True ...  True  True  True]
 [ True  True False ...  True  True  True]]
28
